### ISSUE TITLE
Naming for container roles

### ISSUE THREAD

**Issue by daniel-wtd** [while-true-do/ansible-role-collabora-online#1]
First things first: Awesome, I was thinking about this role, too.

### Type of Report

Bug report

### Actual behaviour

Name of the repo does not clarify, if it is a container role.

### Expected behaviour

Name should provide some hint, that docker is used and there is no plain installation.
I would say one of the below should be used as name:
- ansible-role-docker-collabora
- ansible-role-container-collabora

The README should have a very prominent hint, that this role is using docker beneath it.
This will help users to identify the need of docker and avoid configuration conflicts on hosts, which are not capable of docker or using it in some other ways.

@donvipre  what do you think?

Since this role is quite new it shouldnt be aproblem to rename it.

**Comment by donvipre** [comment]
I agree, that this should reflect the dependency on docker more clearly so I created a new repository with new naming scheme:
https://github.com/while-true-do/ansible-role-docker-collabora
